#ifndef TASK_BLE_H_
#define TASK_BLE_H_

#include "Arduino.h"
#include <BLEDevice.h>
#include <BLEServer.h>
#include <BLEUtils.h>
#include <BLE2902.h>
#include "../Config/config.h"
#include "../PS_FFat/PS_FFat.h"

// See the following for generating UUIDs:
// https://www.uuidgenerator.net/

//#define SERVICE_UUID //Autogenerated from config.h 
//      (if stays the same linux drivers will not recognize updates
#define SERIAL_CHAR_UUID  "beb5483e-36e1-4688-b7f5-ea07361b26a8"
#define FT_CHAR_UUID "b1d3c2c4-7553-11ec-90d6-0242ac120003"

#define BLE_MSG_LEN 500

/* bluetoothctl man menu scan
    uuids 4fafc201-1fb5-459e-8fcc-c5c9c331914b beb5483e-36e1-4688-b7f5-ea07361b26a8 (array[strings]) -> filter to only these uuids
    RSSI -50 (int16) -> filter results to only those w/ RSSI (Received signal strength)
    pathloss uint16 -> filter results to only with tx stronger than specified (I think?)
    duplicateData bool -> disable or enable duplicate detection of advertisement data 
    discoverable bool -> make adapter discoverable or not
    pattern string -> if pattern matches prefix address or device name 
    * Calling any without parameter gives its values
*/

typedef enum bufferIdentification {SERIAL_BUF, FILE_XFER_BUF} buf_ID;

class TaskBLE {
    public: 
        static void init();
        static void run();
        static void setBuffer(buf_ID bufferID, uint8_t* p_newBuffer, size_t len);
    private:
        friend class startIndicateOnRead;
        friend class FT_Callbacks;
        static uint8_t p_serialBuffer[BLE_MSG_LEN];
        static size_t serialBufferLen;
        static uint8_t p_fileXferBuffer[BLE_MSG_LEN];
        static size_t fileXferBufferLen;
        static size_t offset;
        static size_t full_fileSize;
        static BLEServer* pServer;
        static BLECharacteristic* pCharacteristic;
        static BLECharacteristic* p_ftCharacteristic;
        static bool newVal;
        static volatile bool startFT;
        static volatile bool newIndicate;
};
#endif /* TASK_BLE_H_ */

