#ifndef PS_FILE_SYSTEM_H_
#define PS_FILE_SYSTEM_H_

#include "Arduino.h"
#include "../Config/config.h"
#include "FS.h"

#ifdef USE_FFAT
    #include "FFat.h"
    #define fileSystem FFat
#else
    #include "SD.h"
    #include "SPI.h"
    #define fileSystem SD
#endif

/* this needs to match up with the autogenerated file in webFiles.h 
 * requires user to update if changes 
 */
typedef enum fileIndex {DATA, HOME, ICON} fileIndex;

class PS_FileSystem {
    public: 
        static void fullInit();
        static void wakeInit();
        static bool open(File* f, int index, const char* mode);
        static void close(int index);
        static void getmd5Sum(char* output, const char* path);
        static void getmd5Sum(char* output, char* str, uint16_t len);
    private:
        static void verifyFileSystem();
        static void writeExpectedFile(int expectedFileIndex);

        static uint16_t fileLocks;
};
#endif /* PS_FILE_SYSTEM_H_ */

