name: resolve-issue-creation
on: 
  issues:
    types: [opened, edited, reopened]
jobs:
  download-parse-issue-data:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/github-script@v5 
        with: 
          script: | 
            issues = "HelloWorld";
            console.log(issues);

